services:
  # Strapi CMS
  - type: web
    name: fin2excel-cms
    runtime: node
    rootDir: cms
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_e2AMQLEb5vWc@ep-gentle-meadow-ao11993v-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      # Cloudinary Env Vars
      - key: CLOUDINARY_NAME
        value: dbqgjyut7
      - key: CLOUDINARY_KEY
        value: 925333966734263
      - key: CLOUDINARY_SECRET
        value: b8Nw04ZcN6WtMZ-W8kx3nOE4yTE
      # You will need to manually add the Strapi secrets below in the Render Dashboard:
      # APP_KEYS, API_TOKEN_SALT, ADMIN_JWT_SECRET, TRANSFER_TOKEN_SALT, JWT_SECRET
