services:
  # Strapi CMS
  - type: web
    name: fin2excel-cms
    runtime: node
    rootDir: cms
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        sync: false # Set this value in the Render Dashboard
      # Cloudinary Env Vars
      - key: CLOUDINARY_NAME
        sync: false # Set this value in the Render Dashboard
      - key: CLOUDINARY_KEY
        sync: false # Set this value in the Render Dashboard
      - key: CLOUDINARY_SECRET
        sync: false # Set this value in the Render Dashboard
      # You will need to manually add the Strapi secrets below in the Render Dashboard:
      # APP_KEYS, API_TOKEN_SALT, ADMIN_JWT_SECRET, TRANSFER_TOKEN_SALT, JWT_SECRET
